import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/templates/MainHeader";
import Footer from "./components/templates/MainFooter";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "jfloww",
  description: "Generated by jfloww",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-black text-black dark:text-white flex flex-col min-h-screen min-w-screen">
        <SpeedInsights />
        <Header />
        <main className="flex-grow m-auto w-2/3 flex py-8">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
